[workspace]
members = [ 
  "crates/ai-sdk", 
  "crates/providers",
  "crates/utils"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio-stream = "0.1.17"
reqwest = { version = "0.12.15", features = ["json"] }