[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1.45.0", features = ["full"] }
tokio-stream = { workspace = true }
async-trait = "0.1.73"
